# -*- coding: utf-8 -*-
"""Pyscript.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ea4sFeOZd7PcR0P9OUTJv86yMJ92w00R
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df1=pd.read_csv('/content/t1.csv')
df2=pd.read_csv('/content/t2.csv')
df3=pd.read_csv('/content/t3.csv')
tables_excel = pd.concat([df1, df2, df3], ignore_index=True)


tables_excel.to_csv('combined_file.csv', index=False)


tables_excel=pd.read_csv('/content/combined_file.csv')

# tables_excel.head()

tables_excel.columns=range(tables_excel.shape[1])

tables_excel=tables_excel[[8,14,23,44,52,108]]
tables_excel.columns=["MID","Amount","Payment_Mode","CCDC","VPA","UDF2"]
# tables_excel.head(10)

"""#OVERALL PAYMENT METHOD

"""

cc=0
dc=0
upi=0
emi=0

for rows in tables_excel.itertuples():
  if rows.Payment_Mode=="'CREDIT_CARD'":
    cc+=1
  elif rows.Payment_Mode=="'DEBIT_CARD'":
    dc+=1
  elif rows.Payment_Mode=="'UPI'" or rows.Payment_Mode=="'UPI (Credit Card)'" or rows.Payment_Mode=="''UPI_LITE'":
    upi+=1
  elif rows.Payment_Mode=="'EMI'":
    emi+=1

print(f"CC:{cc}\nDC:{dc}\nUPI:{upi}\nEMI:{emi}")

payment_modes = ['CREDIT_CARD', 'DEBIT_CARD', 'UPI', 'EMI']
counts = [cc, dc, upi, emi]
plt.figure(figsize=(6, 3))
plt.bar(payment_modes, counts, color=['red', 'green', 'orange', 'purple'])
plt.title('Payment Mode Counts')
plt.xlabel('Payment Mode')
plt.ylabel('Count')
plt.show()

count_vpa=0
count_cc=0
count_dc=0
count_EMI=0
tot_cc=0
tot_vpa=0
tot_dc=0
tot_emi=0
Dict={}

# good code
dict_count_CC={}
for rows in tables_excel.itertuples():

 pay=rows.Payment_Mode
 if pay == "'CREDIT_CARD'":
     if pd.isna(rows.UDF2):
            continue
     if rows.UDF2 in dict_count_CC:

            if rows.CCDC in dict_count_CC[rows.UDF2][0]:
                dict_count_CC[rows.UDF2][1] += 1
                dict_count_CC[rows.UDF2][2] += rows.Amount
            else:
                dict_count_CC[rows.UDF2][0].append(rows.CCDC)
                dict_count_CC[rows.UDF2][1] += 1
                dict_count_CC[rows.UDF2][2] += rows.Amount
     else:

        dict_count_CC[rows.UDF2] = [[rows.CCDC], 1, rows.Amount]


# print(cc_freq)

df_CC_count = pd.DataFrame.from_dict(dict_count_CC, orient='index', columns=['CC_CARDS','FREQUENCY','Amount'])
df_CC_count.index.name = 'Name'
df_CC_count = df_CC_count.reset_index()

df_sorted_CC_Count=df_CC_count.sort_values('Amount',ascending=False)
df_sorted_CC_Count['Amount'] = df_sorted_CC_Count['Amount'].apply(lambda x: f'{x:,.2f}')
print(df_sorted_CC_Count.to_markdown())

CC_DICT={}
for rows in tables_excel.itertuples():
  ccmode=rows.Payment_Mode
  if ccmode=="'CREDIT_CARD'":
    if pd.isna(rows.UDF2):
            continue
    if rows.UDF2 in CC_DICT:
      if rows.CCDC in CC_DICT[rows.UDF2][0]:
        index = CC_DICT[rows.UDF2][0].index(rows.CCDC)

        CC_DICT[rows.UDF2][1][index] += rows.Amount
      else:
         CC_DICT[rows.UDF2][0].append(rows.CCDC)
         CC_DICT[rows.UDF2][1].append(rows.Amount)

    else:
     CC_DICT[rows.UDF2]=[[rows.CCDC],[rows.Amount]]

DF_COUNT_CC_PER_PERSON=pd.DataFrame.from_dict(CC_DICT,orient='index',columns=['Cards','Amount'])
DF_COUNT_CC_PER_PERSON.index.name='Name'
DF_COUNT_CC_PER_PERSON_SORTED=DF_COUNT_CC_PER_PERSON.sort_values('Name')
print(DF_COUNT_CC_PER_PERSON_SORTED.to_markdown())

"""#DEBIT_CARD"""

# good code
dict_count_DC={}
for rows in tables_excel.itertuples():

 pay=rows.Payment_Mode
 if pay == "'DEBIT_CARD'":
     if pd.isna(rows.UDF2):
            continue
     if rows.UDF2 in dict_count_DC:

            if rows.CCDC in dict_count_DC[rows.UDF2][0]:
                dict_count_DC[rows.UDF2][1] += 1
                dict_count_DC[rows.UDF2][2] += rows.Amount
            else:

                dict_count_DC[rows.UDF2][0].append(rows.CCDC)
                dict_count_DC[rows.UDF2][1] += 1
                dict_count_DC[rows.UDF2][2] += rows.Amount
     else:

            dict_count_DC[rows.UDF2] = [[rows.CCDC], 1, rows.Amount]


# print(cc_freq)

df_DC_count = pd.DataFrame.from_dict(dict_count_DC, orient='index', columns=['DC_CARDS','FREQUENCY','Amount'])
df_DC_count.index.name = 'Name'
df_DC_count = df_DC_count.reset_index()

df_sorted_DC_Count=df_DC_count.sort_values('Amount',ascending=False)
df_sorted_DC_Count['Amount'] = df_sorted_DC_Count['Amount'].apply(lambda x: f'{x:,.2f}')
print(df_sorted_DC_Count.to_markdown())

DC_DICT={}
for rows in tables_excel.itertuples():
  dcmode=rows.Payment_Mode
  if dcmode=="'DEBIT_CARD'":
    if pd.isna(rows.UDF2):
            continue
    if rows.UDF2 in DC_DICT:
      if rows.CCDC in DC_DICT[rows.UDF2][0]:
        index = DC_DICT[rows.UDF2][0].index(rows.CCDC)

        DC_DICT[rows.UDF2][1][index] += rows.Amount
      else:
         DC_DICT[rows.UDF2][0].append(rows.CCDC)
         DC_DICT[rows.UDF2][1].append(rows.Amount)

    else:
     DC_DICT[rows.UDF2]=[[rows.CCDC],[rows.Amount]]

DF_COUNT_DC_PER_PERSON=pd.DataFrame.from_dict(DC_DICT,orient='index',columns=['Cards','Amount'])
DF_COUNT_DC_PER_PERSON.index.name='Name'
DF_COUNT_DC_PER_PERSON_SORTED=DF_COUNT_DC_PER_PERSON.sort_values('Name')
print(DF_COUNT_DC_PER_PERSON_SORTED.to_markdown())

"""#EMI"""

# good code
dict_count_EMI={}
for rows in tables_excel.itertuples():
 pay=rows.Payment_Mode
 if pay == "'EMI'":
     if rows.UDF2 in dict_count_EMI:

            if rows.CCDC in dict_count_EMI[rows.UDF2][0]:
                dict_count_EMI[rows.UDF2][1] += 1
                dict_count_EMI[rows.UDF2][2] += rows.Amount
            else:

                dict_count_EMI[rows.UDF2][0].append(rows.CCDC)
                dict_count_EMI[rows.UDF2][1] += 1
                dict_count_EMI[rows.UDF2][2] += rows.Amount
     else:

            dict_count_EMI[rows.UDF2] = [[rows.CCDC], 1, rows.Amount]


# print(cc_freq)

df_EMI_count = pd.DataFrame.from_dict(dict_count_EMI, orient='index', columns=['EMI_CARDS','FREQUENCY','Amount'])
df_EMI_count.index.name = 'Name'
df_EMI_count = df_EMI_count.reset_index()

df_sorted_EMI_Count=df_EMI_count.sort_values('Amount',ascending=False)
df_sorted_EMI_Count['Amount'] = df_sorted_EMI_Count['Amount'].apply(lambda x: f'{x:,.2f}')
print(df_sorted_EMI_Count.to_markdown())

EMI_DICT={}
for rows in tables_excel.itertuples():
  EMImode=rows.Payment_Mode
  if EMImode=="'EMI'":
    if rows.UDF2 in EMI_DICT:
      if rows.CCDC in EMI_DICT[rows.UDF2][0]:
        index = EMI_DICT[rows.UDF2][0].index(rows.CCDC)

        EMI_DICT[rows.UDF2][1][index] += rows.Amount
      else:
         EMI_DICT[rows.UDF2][0].append(rows.CCDC)
         EMI_DICT[rows.UDF2][1].append(rows.Amount)

    else:
     EMI_DICT[rows.UDF2]=[[rows.CCDC],[rows.Amount]]

DF_COUNT_EMI_PER_PERSON=pd.DataFrame.from_dict(EMI_DICT,orient='index',columns=['Cards','Amount'])
DF_COUNT_EMI_PER_PERSON.index.name='Name'
DF_COUNT_EMI_PER_PERSON_SORTED=DF_COUNT_EMI_PER_PERSON.sort_values('Name')
print(DF_COUNT_EMI_PER_PERSON_SORTED.to_markdown())

"""#UPI

"""

UPI_DICT={}
for rows in tables_excel.itertuples():
  upimode=rows.Payment_Mode
  if upimode=="'UPI'" or upimode=="'UPI (Credit Card)'" or upimode=="''UPI_LITE'":
    if rows.VPA in UPI_DICT:
      UPI_DICT[rows.VPA][0]+=rows.Amount
      UPI_DICT[rows.VPA][1]+=1

    else:
     UPI_DICT[rows.VPA]=[rows.Amount,1]

DF_COUNT_UPI_PER_PERSON=pd.DataFrame.from_dict(UPI_DICT,orient='index',columns=['Amount','Frequency'])
DF_COUNT_UPI_PER_PERSON.index.name='VPA'
DF_COUNT_UPI_PER_PERSON_SORTED=DF_COUNT_UPI_PER_PERSON.sort_values('Amount',ascending=False)
print(DF_COUNT_UPI_PER_PERSON_SORTED.to_markdown())